CREATE TABLE EMP(
EID INT,
ENAME VARCHAR(50),
DEPARTMENT VARCHAR(40),
SALARY DECIMAL(8,2),
JOININGDATE DATETIME,
CITY VARCHAR(50)
);

SELECT *FROM EMP

INSERT INTO EMP VALUES (101,'RAHUL','ADMIN',56000,'1990-JAN-1','RAJKOT')
INSERT INTO EMP VALUES (102,'HARDIK','IT',18000,'1990-SEP-25','AHMEDABAD')
INSERT INTO EMP VALUES (103,'BHAVIN','HR',25000,'1991-MAY-14','BARODA')
INSERT INTO EMP VALUES (104,'BHOOMI','ADMIN',39000,'1991-FEB-8','RAJKOT')
INSERT INTO EMP VALUES (105,'ROHIT','IT',17000,'1990-JUL-23','JAMNAGAR')
INSERT INTO EMP VALUES (106,'PRIYA','IT',9000,'1990-OCT-18','AHMEDABAD')
INSERT INTO EMP VALUES (107,'BHOOMI','HR',34000,'1991-DEC-25','RAJKOT')

--PART A
--1
SELECT MAX(SALARY) AS MAX_SALARY ,MIN(SALARY) AS MIN_SALARY
FROM EMP

--2
SELECT SUM(SALARY) AS TOTAL_SALARY,AVG(SALARY) AS AVG_SALARY
FROM EMP

--3
SELECT COUNT(*) FROM EMP

--4
SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMP
WHERE CITY='RAJKOT'

--5
SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMP
WHERE DEPARTMENT='IT'

--6
SELECT COUNT(*) AS TOTAL_EMP
FROM EMP
WHERE JOININGDATE>'1991-FEB-8'

--7
SELECT AVG(SALARY) AS AVG_SALARY
FROM EMP
WHERE DEPARTMENT='IT'

--8
SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMP
WHERE DEPARTMENT='HR'

--9
SELECT COUNT(DISTINCT CITY) AS UNIQUE_CITY
FROM EMP

--10
SELECT COUNT(DISTINCT DEPARTMENT) AS UNIQUE_DEPARTMENT
FROM EMP

--11
SELECT MIN(SALARY) AS MINIMUM_SALARY
FROM EMP
WHERE CITY='AHMEDABAD'

--12
SELECT CITY, MAX(SALARY) AS HIGHEST_SALARY
FROM EMP
GROUP BY CITY 

--13
SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY
FROM EMP
GROUP BY DEPARTMENT 

--14
SELECT CITY,COUNT(*)
FROM EMP
GROUP BY CITY

--15
SELECT DEPARTMENT,SUM(SALARY)
FROM EMP
GROUP BY DEPARTMENT

--16
SELECT AVG(SALARY)
FROM EMP
GROUP BY DEPARTMENT

--PARTB
--1
SELECT COUNT(CITY)
FROM EMP
WHERE CITY='RAJKOT'

--2
