CREATE TABLE STU_INFO(
	RNO INT,
	NAME VARCHAR(20),
	BRANCH VARCHAR(20)
)


 INSERT INTO STU_INFO VALUES (101,'RAJU','CE'),
							  (102,'AMIT','CE'),
							  (103,'SANJAY','ME'),
							  (104,'NEHA','EC'),
							  (105,'MEERA','EE'),
							  (106,'MAHESH','ME')
SELECT *FROM STU_INFO

CREATE TABLE RESULT(
	RNO INT,
	SPI FLOAT
)

INSERT INTO RESULT VALUES(101,8.8),
						 (102,9.2),
						 (103,7.6),
						 (104,8.2),
						 (105,7.0),
						 (107,8.9)
						 
CREATE TABLE EMPLOYEE_MASTER(
	EMPLOYEENO VARCHAR(30),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(30)
)

INSERT INTO EMPLOYEE_MASTER VALUES('E01','TARUN',NULL),
								  ('E02','ROHAN','E02'),
								  ('E03','PRIYA','E01'),
								  ('E04','MILAN','E03'),
								  ('E05','JAY','E01'),
								  ('E06','ANJANA','E04')
							SELECT *FROM EMPLOYEE_MASTER

--PART A
--1
SELECT * FROM STU_INFO CROSS JOIN RESULT

--2
SELECT * FROM STU_INFO INNER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO

--3
SELECT * FROM STU_INFO LEFT OUTER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO

--4
SELECT * FROM STU_INFO RIGHT OUTER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO

--5
SELECT * FROM STU_INFO FULL OUTER JOIN RESULT ON STU_INFO.RNO = RESULT.RNO

--6
SELECT 
S.RNO,
S.NAME,
S.BRANCH,
R.SPI 
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 

--7
SELECT 
S.RNO,S.NAME,S.BRANCH,R.SPI 
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 
WHERE S.BRANCH='CE'

--8
SELECT 
S.RNO,
S.NAME,
S.BRANCH,
R.SPI 
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 
WHERE S.BRANCH='EC'

--9
SELECT S.BRANCH,AVG(R.SPI) AS AVG_SPI
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 
GROUP BY S.BRANCH

--10
SELECT S.BRANCH,AVG(R.SPI) AS AVG_SPI
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 
WHERE S.BRANCH IN ('EC','CE')
GROUP BY S.BRANCH

--PART B
--1
SELECT S.BRANCH,AVG(R.SPI) AS AVG_SPI
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 
GROUP BY S.BRANCH
ORDER BY AVG_SPI

--2
SELECT S.BRANCH,MAX(R.SPI) AS MAX_SPI
FROM STU_INFO AS S JOIN RESULT AS R ON S.RNO = R.RNO 
GROUP BY S.BRANCH
ORDER BY MAX_SPI DESC

--PART C
--1
SELECT * FROM EMPLOYEE_MASTER
SELECT E.NAME,S.NAME
FROM EMPLOYEE_MASTER AS S RIGHT OUTER JOIN EMPLOYEE_MASTER AS E ON S.EMPLOYEENO = E.MANAGERNO


























