--PART A
CREATE TABLE CRICKET(

NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
)
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('SACHIN TENDULKAR','MUMBAI',30)
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('RAHUL DRAVID','BOMBAY',35)
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('M.S. DHONI','JHARKHAND',31)				
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('SURESH RAINA','GUJRAT',30)
SELECT *FROM CRICKET

SELECT *
INTO WORLDCUP
FROM CRICKET
WHERE 1=1;
SELECT *FROM WORLDCUP


SELECT NAME,CITY
INTO T20 
FROM CRICKET
WHERE 1=2;
SELECT *FROM T20

SELECT *
INTO IPL 
FROM CRICKET
WHERE 1=2;
SELECT *FROM IPL

--PART B

CREATE TABLE EMPLOYEE(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
)

INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES ('JAY PATEL','RAJKOT',30)
INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES ('RAHUL DSVE','BARODA',35)
INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES ('JEET PATEL','SURAT',31)
INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES  ('VIJAY RAVAL','RAJKOT',30)
SELECT *FROM EMPLOYEE

SELECT *
INTO EMPLOYEE_DETAILS
FROM EMPLOYEE
WHERE 1=1;
SELECT *FROM EMPLOYEE_DETAILS

SELECT NAME,CITY
INTO EMPLOYEE_DETAILS1
FROM EMPLOYEE
WHERE 1=2;
SELECT *FROM EMPLOYEE_DETAILS1

SELECT *
INTO EMPLOYEE_DETAILS2
FROM EMPLOYEE
WHERE 1=2;
SELECT *FROM EMPLOYEE_DETAILS2

--PART-C
SELECT *
INTO EMPLOYEE_INFO
FROM EMPLOYEE WHERE 1=2;
SELECT *FROM EMPLOYEE_INFO


INSERT INTO EMPLOYEE_INFO
SELECT *FROM EMPLOYEE
WHERE CITY='RAJKOT'
SELECT *FROM EMPLOYEE_INFO

INSERT INTO EMPLOYEE_INFO
SELECT *FROM EMPLOYEE
WHERE AGE>32
SELECT *FROM EMPLOYEE_INFO

--UPDATE OPERATION

--PART A

--1
 UPDATE DEPOSITE
 SET AMOUNT=5000
 WHERE AMOUNT=3000
 SELECT *FROM DEPOSITE

--2
UPDATE BORROW
SET BNAME='C.G.ROAD'
WHERE CNAME='ANIL'
SELECT *FROM BORROW

--3
UPDATE DEPOSITE
SET ACTNO=111,AMOUNT=5000
WHERE BNAME='SANDIP'
SELECT *FROM DEPOSITE

--4
UPDATE DEPOSITE
SET AMOUNT=7000
WHERE CNAME='KRANTI'
SELECT *FROM DEPOSITE

--5
UPDATE DEPOSITE
SET BNAME='ANDHERI WEST'
WHERE BNAME='ANDHERI'
SELECT *FROM DEPOSITE

--6
UPDATE DEPOSITE
SET BNAME='NEHRU PALACE'
WHERE CNAME='MEHUL'
SELECT *FROM DEPOSITE

--7
UPDATE DEPOSITE
SET AMOUNT=5000
WHERE ACTNO BETWEEN 103 AND 107
SELECT *FROM DEPOSITE

--8
UPDATE DEPOSITE
SET ADATE='1995-4-1'
WHERE CNAME='ANIL'
SELECT *FROM DEPOSITE

--9
UPDATE DEPOSITE
SET AMOUNT=10000
WHERE CNAME='MINU'
SELECT *FROM DEPOSITE

--10
UPDATE DEPOSITE
SET AMOUNT=5000,ADATE='1996-4-1'
WHERE CNAME='PRAMOD'
SELECT *FROM DEPOSITE

--PART B
--1
UPDATE BORROW
SET AMOUNT=AMOUNT+(AMOUNT)*0.10
SELECT * FROM BORROW

--2
UPDATE DEPOSITE
SET AMOUNT=AMOUNT+(AMOUNT)*0.20
SELECT *FROM DEPOSITE

--PART C
--1
UPDATE BORROW
SET AMOUNT=NULL
WHERE LOANNO=321
SELECT *FROM BORROW

--2
UPDATE BORROW
SET BNAME=NULL
WHERE CNAME='KRANTI'
SELECT *FROM BORROW

--3
SELECT *FROM BORROW WHERE AMOUNT IS NULL

--4
SELECT *FROM BORROW WHERE BNAME IS NOT NULL

--5
UPDATE BORROW
SET AMOUNT=5000,BNAME='VRCE',CNAME='DARSHAN'
WHERE LOANNO=481
SELECT *FROM BORROW

--6
UPDATE DEPOSITE
SET ADATE='2021-1-1'
WHERE AMOUNT<2000
SELECT *FROM DEPOSITE

--7
UPDATE DEPOSITE 
SET ADATE=NULL,BNAME='ANDHERI'
WHERE ACTNO=110
SELECT *FROM DEPOSITE


