--PART A
CREATE TABLE STUDENT_INFO(
	RNO INT,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50),
	SPI FLOAT,
	BKLOG INT
)

INSERT INTO STUDENT_INFO VALUES(101,'RAJU','CE',8.80,0)
INSERT INTO STUDENT_INFO VALUES(102,'AMIT','CE',2.20,3)
INSERT INTO STUDENT_INFO VALUES(103,'SANJAY','ME',1.50,6)
INSERT INTO STUDENT_INFO VALUES(104,'NEHA','EC',7.65,1)
INSERT INTO STUDENT_INFO VALUES(105,'MEERA','EE',5.52,2)
INSERT INTO STUDENT_INFO VALUES(106,'MAHESH','EC',4.50,3)

SELECT * FROM STUDENT_INFO

--1
CREATE VIEW PERSONAL AS SELECT * FROM STUDENT_INFO

--2
CREATE VIEW STUDENT_DETAILS AS SELECT NAME,BRANCH,SPI FROM STUDENT_INFO

--3
CREATE VIEW AcademicData AS SELECT RNO,NAME,BRANCH FROM STUDENT_INFO

--4
CREATE VIEW STUDENT_BKLOG AS SELECT * FROM STUDENT_INFO WHERE BKLOG>2

--5
CREATE VIEW STUDENT_PATTERN AS SELECT RNO,NAME,BRANCH FROM STUDENT_INFO WHERE NAME LIKE '____'

--6
INSERT INTO AcademicData VALUES (107,'MEET','ME')

--7
UPDATE STUDENT_DETAILS 
SET BRANCH='ME'
WHERE NAME='AMIT'

--8
DELETE FROM AcademicData WHERE RNO=104

--PART B
--1
CREATE VIEW SPI
AS SELECT *FROM STUDENT_INFO WHERE SPI>8.5

--2
CREATE VIEW BKLOG
AS SELECT *FROM STUDENT_INFO WHERE BKLOG=0

--3
CREATE VIEW COMPUTERVIEW
AS SELECT *FROM STUDENT_INFO WHERE BRANCH='CE'

--PART C
--1
CREATE VIEW RESULT_EC AS
SELECT NAME,SPI FROM STUDENT_INFO WHERE SPI<5 AND BRANCH = 'EC'

--2
UPDATE RESULT_EC SET SPI=4.90 WHERE NAME='MAHESH'

--3
CREATE VIEW STU_BKLOG AS 
SELECT RNO,NAME,BKLOG FROM STUDENT_INFO WHERE NAME LIKE 'M%' AND BKLOG>5
--4
DROP VIEW COMPUTERVIEW














































