SELECT * FROM PERSON
--PART A
--1
SELECT DEPARTMENTNAME,DEPARTMENTCODE FROM DEPT

--2
SELECT DEPT.DEPARTMENTNAME,PERSON.PERSONNAME FROM DEPT JOIN PERSON 
ON DEPT.DEPARTMENTID = PERSON.DEPARTMENTID 
WHERE DEPT.LOCATION='C-BLOCK'

--3
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME FROM DEPT D JOIN PERSON P
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE P.CITY='JAMNAGAR'

--4
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME FROM DEPT D JOIN PERSON P
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE CITY<>'RAJKOT'

--5
SELECT P.PERSONNAME FROM DEPT D JOIN PERSON P
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE D.DEPARTMENTNAME='CIVIL' AND P.JOININGDATE>'2001-08-01'

--6
SELECT * FROM DEPT D JOIN PERSON P
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE D.DEPARTMENTNAME='COMPUTER'

--7
SELECT P.PERSONNAME,D.DEPARTMENTNAME FROM DEPT D JOIN PERSON P
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE DATEDIFF(DAY,JOININGDATE,'2024-08-20')>=365

--8
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONNAME) FROM DEPT D JOIN PERSON P 
ON D.DEPARTMENTID=P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--9
SELECT D.DEPARTMENTNAME,MAX(P.SALARY),MIN(P.SALARY) FROM DEPT D JOIN PERSON P 
ON D.DEPARTMENTID=P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--10
SELECT P.CITY,AVG(P.SALARY),MAX(P.SALARY),MIN(P.SALARY) FROM DEPT D JOIN PERSON P 
ON D.DEPARTMENTID=P.DEPARTMENTID
GROUP BY P.CITY

--11
SELECT AVG(P.SALARY) FROM DEPT D JOIN PERSON P 
ON D.DEPARTMENTID=P.DEPARTMENTID
WHERE CITY='AHMEDABAD'

--12
SELECT PERSONNAME + 'LIVES IN' + CITY+'AND WORKS IN' + D.DEPARTMENTNAME +'DEPARTMENT' FROM PERSON P FULL OUTER JOIN DEPT D ON D.DEPARTMENTID=P.DEPARTMENTID
























