CREATE TABLE SALES_DATA(
REGION VARCHAR(100),
PRODUCT VARCHAR(50),
SALES_AMOUNT DECIMAL(8,2),
YEAR INT
)
SELECT *FROM SALES_DATA

INSERT INTO SALES_DATA VALUES('NORTH AMERICA','WATCH',1500,2023)
INSERT INTO SALES_DATA VALUES('EUROPE','MOBILE',1200,2023)
INSERT INTO SALES_DATA VALUES('ASIA','WATCH',1800,2023)
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','TV',900,2024)
INSERT INTO SALES_DATA VALUES('EUROPE','WATCH',2000,2024)
INSERT INTO SALES_DATA VALUES('ASIA','MOBILE',1000,2024)
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','MOBILE',1600,2023)
INSERT INTO SALES_DATA VALUES('EUROPE','TV',1500,2023)
INSERT INTO SALES_DATA VALUES('ASIA','TV',1100,2024)
INSERT INTO SALES_DATA VALUES('NORTH AMERICA','WATCH',1700,2024)

--PART A
--1
SELECT SUM(SALES_AMOUNT) AS TOTAL_AMOUNT,REGION
FROM SALES_DATA
GROUP BY REGION

--2
SELECT AVG(SALES_AMOUNT) AS AVG_AMOUNT,PRODUCT
FROM SALES_DATA
GROUP BY PRODUCT

--3
SELECT YEAR, MIN(SALES_AMOUNT) AS MIN_AMOUNT
FROM SALES_DATA
GROUP BY YEAR

--4
SELECT MIN(SALES_AMOUNT) AS TOTAL_AMOUNT,REGION,YEAR
FROM SALES_DATA
GROUP BY REGION,YEAR

--5
SELECT COUNT(PRODUCT),REGION
FROM SALES_DATA
GROUP BY REGION

--6
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT,YEAR,PRODUCT 
FROM SALES_DATA
GROUP BY YEAR,PRODUCT

--7
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT,REGION 
FROM SALES_DATA
GROUP BY REGION
HAVING SUM(SALES_AMOUNT)>5000

--8
SELECT AVG(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT,PRODUCT 
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT)<10000

--9
SELECT MAX(SALES_AMOUNT) AS MAX_SALES_AMOUNT,YEAR 
FROM SALES_DATA
GROUP BY YEAR
HAVING MAX(SALES_AMOUNT)>500

--10
SELECT COUNT(DISTINCT PRODUCT) AS DISTINCT_PRODUCT,REGION 
FROM SALES_DATA
GROUP BY REGION
HAVING COUNT(DISTINCT PRODUCT)>=3

--11
SELECT MIN(SALES_AMOUNT) AS MIN_SALES_AMOUNT,YEAR 
FROM SALES_DATA
GROUP BY YEAR
HAVING MIN(SALES_AMOUNT)<1000

--12
SELECT SALES_AMOUNT,REGION
FROM SALES_DATA
WHERE YEAR=2023

--PART B
--1
SELECT COUNT(REGION) AS TOTAL_REGION,REGION,YEAR 
FROM SALES_DATA
GROUP BY REGION,YEAR
ORDER BY REGION,YEAR 

--2
SELECT MAX(SALES_AMOUNT) AS TOTAL_AMOUNT,REGION
FROM SALES_DATA
GROUP BY REGION
HAVING MAX(SALES_AMOUNT)>1000
ORDER BY REGION

--3
SELECT SUM(SALES_AMOUNT) AS TOTAL_AMOUNT,YEAR
FROM SALES_DATA
GROUP BY YEAR
HAVING SUM(SALES_AMOUNT)>1000
ORDER BY YEAR DESC

--4
SELECT TOP 3 SUM(SALES_AMOUNT) , REGION 
FROM SALES_DATA
WHERE YEAR=2024
GROUP BY REGION

--PART C
--1
SELECT AVG(SALES_AMOUNT),PRODUCT 
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000
ORDER BY PRODUCT

--2
SELECT REGION,YEAR, COUNT(PRODUCT) 
FROM SALES_DATA
GROUP BY REGION,YEAR
HAVING COUNT(PRODUCT)>5
ORDER BY REGION,YEAR

--3
SELECT AVG(SALES_AMOUNT),YEAR
FROM SALES_DATA
WHERE YEAR=2023
GROUP BY SALES_AMOUNT,YEAR
HAVING AVG(SALES_AMOUNT)>1500
ORDER BY SALES_AMOUNT,YEAR DESC

--4
SELECT COUNT(PRODUCT),REGION
FROM SALES_DATA
GROUP BY PRODUCT,REGION
HAVING COUNT(PRODUCT)>1

--5
SELECT MAX(SALES_AMOUNT),REGION
FROM SALES_DATA
GROUP BY REGION

