--PART A
CREATE TABLE STUDENT(
STUID INT,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(25),
CITY VARCHAR(25),
ADDRESS VARCHAR(25)
)

SELECT * FROM STUDENT
	
INSERT INTO STUDENT VALUES(1011,'KEYUR','PATEL','TECHONTHENET.COM','RAJKOT','A-303 "VASANT KUNJ",RAJKOT')	
INSERT INTO STUDENT VALUES(1022,'HARDIK','SHAH','DIGMINECRAFT.COM','AHMEDABAD','"RAM KRUPA",RAIYA ROAD')
INSERT INTO STUDENT VALUES(1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA','RAJ BHAVAN PLOT, NEAR GARDEN')
INSERT INTO STUDENT VALUES(1044,'BHOOMI','GAJERA','CHECKYOURMATH.COM','AHMEDABAD','"JIGS HOME",NAROL')
INSERT INTO STUDENT VALUES(1055,'HARMIT','MITEL','@ME.DARSHAN.COM','RAJKOT','B-55, RAJ RESIDENCY')
INSERT INTO STUDENT VALUES(1066,'ASHOK','JANI',NULL,'BARODA','A502,CLUB HOUSE BUILDING')

--1
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE 'A%'

--2
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '_____'

--3
SELECT FIRSTNAME,LASTNAME FROM STUDENT
WHERE CITY LIKE '_____A'

--4
SELECT LASTNAME FROM STUDENT
WHERE LASTNAME LIKE '%TEL'

--5
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE 'HA%%T'

--6
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE 'K_Y%'

--7
SELECT FIRSTNAME FROM STUDENT
WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'

--8
SELECT LASTNAME FROM STUDENT
WHERE LASTNAME LIKE '%JER%'

--9
SELECT CITY FROM STUDENT
WHERE CITY LIKE '[R,B]%'

--10
SELECT FIRSTNAME FROM STUDENT
WHERE WEBSITE IS NOT NULL

--11
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '[A-H]%'

--12
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%'

--13
SELECT FIRSTNAME FROM STUDENT
WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'

--14
SELECT LASTNAME FROM STUDENT
WHERE LASTNAME LIKE 'PAT%'

--15
SELECT CITY FROM STUDENT
WHERE CITY NOT LIKE 'B%'

--PART B
--1
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '[A-H]%'

--2
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE 'H[A,E,I,O,U]%'

--3
SELECT LASTNAME FROM STUDENT
WHERE LASTNAME NOT LIKE '%A'

--4
SELECT LASTNAME FROM STUDENT
WHERE LASTNAME NOT LIKE '[A,E,I,O,U]%'

--5
SELECT WEBSITE FROM STUDENT
WHERE WEBSITE LIKE '%.NET%'

--PART C
--1
SELECT ADDRESS FROM STUDENT
WHERE ADDRESS LIKE '%-%'

--2
SELECT ADDRESS FROM STUDENT
WHERE ADDRESS LIKE '%['',""]%'

--3
SELECT WEBSITE FROM STUDENT
WHERE WEBSITE LIKE '%@%'

--4
SELECT FIRSTNAME FROM STUDENT
WHERE FIRSTNAME LIKE '____ ' OR FIRSTNAME LIKE'_____'














