--PART a
--1
ALTER TABLE DEPOSITE
ADD CITY VARCHAR(20),PINCODE INT
SELECT *FROM DEPOSITE

--2
ALTER TABLE DEPOSITE
ALTER COLUMN CNAME VARCHAR(35)
SELECT *FROM DEPOSITE 

--3
ALTER TABLE DEPOSITE
ALTER COLUMN AMOUNT INT
SELECT *FROM DEPOSITE

--4
SP_RENAME 'DEPOSITE.ACTNO', 'ANO', 'COLUMN'
SELECT *FROM DEPOSITE

--5
ALTER TABLE DEPOSITE
DROP COLUMN CITY
SELECT *FROM DEPOSITE

--6
SP_RENAME 'DEPOSITE','DEPOSITE_DETAIL'

--PART B
--1                                                                     
SP_RENAME 'DEPOSITE_DETAIL.ADATE','AOPENDATE','COLUMN'
SELECT *FROM DEPOSITE_DETAIL

--2
ALTER TABLE DEPOSITE_DETAIL
DROP COLUMN AOPENDATE
SELECT *FROM DEPOSITE_DETAIL

--3
SP_RENAME 'DEPOSITE_DETAIL.CNAME','CUSTOMERNAME','COLUMN'
SELECT *FROM DEPOSITE_DETAIL

--PART C
CREATE TABLE STUDENT_DETAIL(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(20),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)
--1
ALTER TABLE STUDENT_DETAIL
ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL
SELECT *FROM STUDENT_DETAIL

--2
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN NAME VARCHAR(35)
SELECT *FROM STUDENT_DETAIL 

--3
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT
SELECT *FROM STUDENT_DETAIL

--4
SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO','COLUMN'
SELECT *FROM STUDENT_DETAIL

--5
ALTER TABLE STUDENT_DETAIL
DROP COLUMN CITY
SELECT *FROM STUDENT_DETAIL

--6
SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'

--DELETE,TRUNCATE,DROP
--PART A
--1
DELETE FROM DEPOSITE_DETAIL
WHERE AMOUNT>=4000
SELECT *FROM DEPOSITE_DETAIL

--2
DELETE FROM DEPOSITE_DETAIL
WHERE BNAME='CHANDI'
SELECT *FROM DEPOSITE_DETAIL

--3
DELETE FROM DEPOSITE_DETAIL
WHERE ANO>105
SELECT *FROM DEPOSITE_DETAIL

--5
TRUNCATE TABLE DEPOSITE_DETAIL 
SELECT *FROM DEPOSITE_DETAIL

--6
DROP TABLE DEPOSITE_DETAIL
SELECT *FROM DEPOSITE_DETAIL





















